FROM node:22

ENV NODE_ENV=docker
# create app directory
WORKDIR /app

COPY ./test-data-server/. .

RUN npm install

# Bundle app source
RUN npm run build:docker

COPY ./security/mock-data-holder/tls/nodejs-data-holder.pfx /app/dist/src/security/nodejs-data-holder.pfx
COPY ./security/mock-data-holder/tls/nodejs-data-holder.pem /app/dist/src/security/nodejs-data-holder.pem
COPY ./security/mock-data-holder/tls/nodejs-data-holder.key /app/dist/src/security/nodejs-data-holder.key

COPY ./security/mtls-gateway/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN  update-ca-certificates

# These can be disabled for ssh debugging purposes
# RUN apt-get update
# RUN apt-get -y install -y iputils-ping
# RUN apt-get -y install -y ssh
# RUN apt-get -y install vim

CMD [ "node", "dist/src/app.js"]


EXPOSE 3005
