FROM cdr-auth-server:accc-dsb AS build


# copy the certificate 
COPY ./test-data-server/security/accc-certs/cdr-auth-server/tls/tls-server.pfx /app/cdrauthserver/Certificates
COPY ./configs/auth-server/appsettings.Release.json /app/cdrauthserver