FROM consumerdataright/mock-data-recipient AS build


COPY ./configs/adr/appsettings.Release.json /app/web/appsettings.Release.json
COPY ./configs/certificates/dsb-client.pfx /app/web/Certificates/dsb-client.pfx
COPY ./configs/certificates/dsb-server.pfx /app/web/Certificates/dsb-server.pfx
