FROM cdradmin/cdr-auth-server:0.1 AS build

# copy the certificate 
COPY ./security/tls-gateway/tls-server.pfx /app/cdrauthserver/Certificates
COPY ./configs/auth-server/appsettings.Release.json /app/cdrauthserver
