# the image is build from  https://github.com/ConsumerDataStandardsAustralia/accc-authorisation-server
FROM consumerdatastandardsaustralia/tls-gateway:aws01 AS build

WORKDIR /app

COPY ./configs/tls-gateway/gateway-config.json /app/gateway-tls/
COPY ./configs/certificates/dsb-server.pfx /app/gateway-tls/Certificates/dsb-server.pfx
COPY ./configs/certificates/dsb-server.key /app/gateway-tls/Certificates/dsb-server.key
