# the image is build from  https://github.com/ConsumerDataStandardsAustralia/accc-authorisation-server
FROM consumerdatastandardsaustralia/mtls-gateway:0.1 AS build


WORKDIR /app

COPY ./configs/mtls-gateway/gateway-config.json /app/gateway-mtls/
COPY ./configs/certificates/server.pfx /app/gateway-mtls/Certificates/server.pfx 

