FROM node:18

ENV NODE_ENV=docker
# Create app directory
WORKDIR /usr/src/app

COPY load-test-data/package*.json ./

RUN npm install

# Bundle app source
COPY ./load-test-data/ .
COPY ./utils/sql/AddClientScriptRelease.sql .

RUN npm run build

# These can be disabled for ssh debugging purposes
# RUN apt-get update
# RUN apt-get -y install -y iputils-ping
# RUN apt-get -y install -y ssh
# RUN apt-get -y install vim

CMD [ "node", "dist/app.js"]
