FROM mtls-gateway:accc AS build


WORKDIR /app

# COPY ./configs/mtls-gateway/gateway-config.json /app/gateway-mtls/
# COPY ./test-data-server/security/accc-certs/mtls-gateway/mtls-server.pfx /app/gateway-mtls/Certificates

