FROM consumerdatastandardsaustralia/authserver-ui:aws01

COPY ./test-data-server/resources/cdr-logo.png /usr/share/nginx/html

COPY ./configs/certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
COPY ./configs/auth-server/nginx/nginx.conf /etc/nginx/conf.d/nginx.conf

COPY ./configs/certificates/authserver-ui.pem /etc/nginx/ssl/authserver-ui.pem
COPY ./configs/certificates/authserver-ui.key /etc/nginx/ssl/authserver-ui.key