FROM node:16

ENV NODE_ENV=docker
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY load-test-data/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./load-test-data/ .

RUN npm run build

CMD [ "node", "dist/app.js"]
